# Generated by Django 4.1.1 on 2022-09-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Products", new_name="Product",),
    ]
